### PR TITLE
Use updated fork of ShellCheck

### PR DESCRIPTION
**Pull request by yochananmarqos**

### CODE REVIEW

**Comment by lwindolf** [comment]
I just checked the referenced repo and it doesn't exist. Are you sure "elbosso/gedit-shellcheck" is correct?

**Comment by yochananmarqos** [comment]
It exists: https://github.com/elbosso/gedit-shellcheck

**Comment by lwindolf** [comment]
Sorry for the late review. Thanks for the cool improvement!

**Comment by lwindolf** [comment]
Sorry, about the double confusion:

1. I mistyped when searching for the repo
2. After merging your PR I found the PR of the author back-merging his fixes.

Therefore I reverted this PR here.

**Pull request merged**
